# Generated by Django 2.1 on 2018-08-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementline',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type': 'SIMPLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_lines', to='products.Product'),
        ),
    ]
