# Generated by Django 2.1 on 2018-08-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180811_1614'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorderline',
            options={'ordering': ['sale_order', 'kit', 'product'], 'verbose_name': 'Linha do Pedido', 'verbose_name_plural': 'Linhas dos Pedidos'},
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='attribute_name',
            field=models.CharField(default='DEFAULT', max_length=40, verbose_name='Atributo'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='kit',
            field=models.ForeignKey(limit_choices_to={'type': 'KIT'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_order_lines', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('ORDER_PLACED', 'Pedido Realizado'), ('SEPARATION_IN_STOCK', 'Em Separação no Estoque'), ('MOUNTING', 'Em Montagem'), ('REALIZATION_OF_TESTS', 'Realização de Testes'), ('DONE', 'Concluído')], default='ORDER_PLACED', max_length=40, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type': 'SIMPLE'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_order_lines', to='products.Product'),
        ),
    ]
