# Generated by Django 2.1 on 2018-08-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180812_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorderline',
            old_name='attribute_name',
            new_name='attribute',
        ),
    ]
