# Generated by Django 2.1 on 2018-08-10 20:00

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitattribute',
            name='kit',
            field=models.ForeignKey(limit_choices_to={'type': 'KIT'}, on_delete=django.db.models.deletion.CASCADE, related_name='kit_attributes', to='products.Product', validators=[apps.products.models.validate_kit], verbose_name='Kit'),
        ),
    ]
