# Generated by Django 2.1 on 2018-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180810_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='kitattribute',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Nome'),
        ),
    ]
