# Generated by Django 2.1 on 2018-08-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180811_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kitattribute',
            unique_together={('kit', 'name')},
        ),
    ]
