# Generated by Django 2.1 on 2018-08-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180811_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitattvalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.KitAttribute', verbose_name='Atributo'),
        ),
    ]
